// Writes sim_c/build/tables.h: the static data the C battle engine needs, taken from DaddyDrago's engine at the
// pinned commit (run by setup.sh; the output is gitignored, like his code). Card definitions, ability names, his
// card sets and random pools, and per (card, border) values computed by his own functions, so the C engine never
// re-derives a number his code computes.
//   npx tsx gen_tables.ts ../sim_c/build/tables.h
import { mkdirSync, writeFileSync } from 'node:fs'
import { dirname } from 'node:path'
import cards from './vendor/CardRngExpansionDepths/src/data/cards'
import { cardAge } from './vendor/CardRngExpansionDepths/src/data/ages'
import { AVIAN_CARDS, DEMON_CARDS, DRAGON_CARDS, IMP_BOOSTED_CARDS, RNG_ABILITIES, UNDEAD_CARDS } from './vendor/CardRngExpansionDepths/src/engine/combat-data'
import { getAttack, getHealth, getPower, rarityWithBorders } from './vendor/CardRngExpansionDepths/src/engine/stats.label'
import { TOY_CARD_NAMES } from './vendor/CardRngExpansionDepths/src/engine/auras.label'
import { CONSTELLAR_ABILITIES, DODGE_ABILITIES, FULLY_SUPPORTED, NUWA_CREATABLE_POOL, PANDORA_ABILITY_POOL, RANDOM_CARD_POOL }
  from './vendor/CardRngExpansionDepths/src/engine/battle-v2.label'

const out = process.argv[2]
// Border ids 1-16 in our order; each is the border list our loadouts pass (card_engine/simulator/drago.py).
const CODES = ['', 'Pl', 'Cr', 'CrPl', 'Ru', 'RuPl', 'RuCr', 'RuCrPl', 'Ga', 'GaPl', 'GaCr', 'GaCrPl', 'GaRu', 'GaRuPl', 'GaRuCr', 'GaRuCrPl']
const PARTS: Record<string, string> = { Ga: 'Galaxy', Ru: 'Ruby', Cr: 'Crystal', Pl: 'Platinum' }
const BORDERS = CODES.map((code) => (code.match(/../g) || []).map((part) => PARTS[part]))

const sanitize = (name: string) => name.normalize('NFKD').replace(/[^\x00-\x7f]/g, '').toUpperCase().replace(/[^A-Z0-9]+/g, '_').replace(/^_|_$/g, '')
const num = (x: number) => { if (!Number.isFinite(x)) throw new Error('non-finite table value'); const t = String(x); return /[.e]/.test(t) ? t : t + '.0' }  // a double literal
const str = (s: string) => JSON.stringify(s)

// Every ability name the engine can meet: card abilities, his supported list (Pandora's pool), Constellar forms,
// and names his battle code assigns or compares that no card holds.
const extra = ['Heart Hunter', 'Mastered Ascension', 'Safeguarding', 'Mother of Dragons', 'Twelve Devas Axe', 'Vajra Short Sword',
  'Staff of Perfect Enlightenment', 'Shield of Ahimsa', 'War Scythe', 'Great Nirvana Sword - Zero', 'Joy', 'Sorrow']
const abilities = [...new Set([...cards.map((c: any) => c.ability).filter(Boolean), ...FULLY_SUPPORTED, ...CONSTELLAR_ABILITIES,
  ...RNG_ABILITIES, ...extra])].sort()
const abilityId = new Map(abilities.map((name, i) => [name, i]))
const lines: string[] = ['// Generated by sim_js/gen_tables.ts from DaddyDrago\'s engine; do not edit or commit.', '#pragma once', '']
const unique = (kind: string, names: string[]) => {
  const seen = new Map<string, string>()
  for (const name of names) {
    const key = sanitize(name)
    if (seen.has(key) && seen.get(key) !== name) throw new Error(`${kind} names ${seen.get(key)} and ${name} collide`)
    seen.set(key, name)
  }
}
unique('ability', abilities)
unique('card', cards.map((c: any) => c.name))
lines.push(`#define NABILITY ${abilities.length}`)
abilities.forEach((name, i) => lines.push(`#define A_${sanitize(name)} ${i}`))
lines.push(`static const char *const ABILITY_NAMES[NABILITY] = {${abilities.map(str).join(', ')}};`)
lines.push(`static const unsigned char ABILITY_SUPPORTED[NABILITY] = {${abilities.map((a) => FULLY_SUPPORTED.has(a) ? 1 : 0).join(', ')}};`)
lines.push(`static const unsigned char ABILITY_DODGE[NABILITY] = {${abilities.map((a) => DODGE_ABILITIES.has(a) ? 1 : 0).join(', ')}};`)

lines.push('', `#define NDEF ${cards.length}`)
cards.forEach((c: any, i: number) => lines.push(`#define D_${sanitize(c.name)} ${i}`))
const field = (name: string, type: string, values: (string | number)[]) =>
  lines.push(`static const ${type} ${name}[NDEF] = {${values.join(', ')}};`)
field('DEF_NAME', 'char *const', cards.map((c: any) => str(c.name)))
field('DEF_ABILITY', 'short', cards.map((c: any) => c.ability ? abilityId.get(c.ability)! : -1))
field('DEF_HP_MULTIPLIER', 'double', cards.map((c: any) => num(c.hpMultiplier || 1)))
field('DEF_AGE', 'double', cards.map((c: any) => num(cardAge(c.name))))
field('DEF_TIME_STORM', 'unsigned char', cards.map((c: any) => c.weather === 'Time Storm' ? 1 : 0))
field('DEF_BOSS', 'unsigned char', cards.map((c: any) => c.boss ? 1 : 0))
const sets: [string, (c: any) => boolean][] = [
  ['UNDEAD', (c) => UNDEAD_CARDS.has(c.name)], ['DEMON', (c) => DEMON_CARDS.has(c.name)], ['DRAGON', (c) => DRAGON_CARDS.has(c.name)],
  ['AVIAN', (c) => AVIAN_CARDS.has(c.name)], ['IMP', (c) => IMP_BOOSTED_CARDS.has(c.name)], ['TOY', (c) => TOY_CARD_NAMES.has(c.name)],
  ['RNG_ABILITY', (c) => Boolean(c.ability && RNG_ABILITIES.has(c.ability))],
]
sets.forEach(([name], bit) => lines.push(`#define SET_${name} ${1 << bit}`))
field('DEF_SETS', 'unsigned char', cards.map((c: any) => sets.reduce((m, [, has], bit) => m | (has(c) ? 1 << bit : 0), 0)))

// Per (card, border id 1-16): rarity with borders and the base power/health/attack his makePlayerCard would give.
const table = (name: string, f: (c: any, borders: any) => number) => lines.push(
  `static const double ${name}[NDEF][17] = {${cards.map((c: any) => `{0, ${BORDERS.map((b) => num(f(c, b))).join(', ')}}`).join(',\n  ')}};`)
table('DEF_RARITY', (c, b) => rarityWithBorders(c, b))
table('DEF_POWER', (c, b) => getPower(c, b))
table('DEF_HEALTH', (c, b) => getHealth(c, b))
table('DEF_ATTACK', (c, b) => getAttack(c, b))

const pool = (name: string, ids: number[]) =>
  lines.push(`#define N${name} ${ids.length}`, `static const short ${name}[N${name}] = {${ids.join(', ')}};`)
const defIndex = new Map(cards.map((c: any, i: number) => [c, i]))
pool('PANDORA_POOL', PANDORA_ABILITY_POOL.map((a: string) => abilityId.get(a)!))
pool('RANDOM_CARD_POOL', RANDOM_CARD_POOL.map((c: any) => defIndex.get(c)!))
pool('NUWA_POOL', NUWA_CREATABLE_POOL.map((c: any) => defIndex.get(c)!))
pool('CONSTELLAR_POOL', CONSTELLAR_ABILITIES.map((a: string) => abilityId.get(a)!))
lines.push(`static const char *const BORDER_CODES[17] = {"", ${CODES.map(str).join(', ')}};`)

mkdirSync(dirname(out), { recursive: true })
writeFileSync(out, lines.join('\n') + '\n')
console.error(`tables: ${cards.length} cards, ${abilities.length} abilities`)
