"""Incomplete mode: a team's chances against the strong teams it cannot see (user, 2026-10-06).

The mode is for PvP: you do not know who will attack you, and your attackers do not know your team. A team built in
incomplete mode is one that works against strong teams in general. So the unseen side is not a random team but the
*field*, strong teams generated by the model itself and kept only if the engine confirms them; as the model gets
stronger the field gets stronger, and the hidden side's meaning moves with it (user: "the hidden slots meaning
should change as the model gets stronger").

The field (data/labels/field/field_<generation>.json) holds two populations by self-play:
  - attackers, scored by the engine against the previous generation's defenders;
  - defenders, scored against the previous generation's attackers.
Each generation's candidates are the previous field's members (kept only if they still score), the model's own
proposals in incomplete mode (training.generate, Settings.incomplete), counters to field members, and one-change
variants of members (training.hard.mutate). Generation 0 starts from the generator's broadly ascended teams.

Labels (hidden_<generation * GENERATION_SEEDS + n>.npz, mined like training.hard's): each round takes one role and
48 candidate teams (field members, their variants, the model's proposals and random teams), plays each against
--opponents members of the other role's field (a fresh draw per team), and takes the mean win chance as the soft
label. The model scores the same teams in incomplete mode, and the rows it gets most wrong (each two places apart
from the others) and a few others are kept. A visible attacker is side A with side B hidden; a visible defender is
side B with side A hidden. The trainer reads only the newest generations' shards (train.py --field-generations).

    python -m card_engine.training.incomplete field --checkpoint data/training_18t/ema.checkpoint
    python -m card_engine.training.incomplete labels --shards 10 --checkpoint data/training_18t/ema.checkpoint
"""

import argparse
import json
import multiprocessing as mp
import os
import random
import time
from concurrent.futures import ProcessPoolExecutor
from pathlib import Path

import numpy as np

from ..catalog import load_catalog
from ..teams import spec
from .hard import distinct, draw_candidate, mutate
from .labels import FIELDS, GENERATION_SEEDS, HIDDEN_TEAM, SHARD_DIR, STORE, evaluate, next_seed, random_spec

FIELD_DIR = SHARD_DIR / "field"
ROLES = ("attack", "defend")
ALL_BORDERS = tuple(range(1, 17))  # the theoretical space, as the rest of training uses


def _init():
    global _CATALOG
    _CATALOG = load_catalog()


def _match(job):
    """The attacker's (side A's) win chance against the defender, by the engine; nan if it never finishes."""
    attacker, defender, seed = job
    probs, _ = evaluate(_CATALOG, spec(attacker, defender), seed)
    finished = probs[0] + probs[1]
    return probs[0] / finished if finished > 0 else float("nan")


def team_scores(pool, teams, role, opponents, seed):
    """Each team's mean engine win chance in `role` against its own list of opponents ([[team]] per team)."""
    jobs, owners = [], []
    for index, (team, against) in enumerate(zip(teams, opponents)):
        for j, opponent in enumerate(against):
            jobs.append(((team, opponent) if role == 0 else (opponent, team), seed + len(jobs)))
            owners.append(index)
    wins = [[] for _ in teams]
    for owner, a_win in zip(owners, pool.map(_match, [(a, b, s) for (a, b), s in jobs], chunksize=8)):
        if not np.isnan(a_win):
            wins[owner].append(a_win if role == 0 else 1 - a_win)
    return np.array([np.mean(w) if w else np.nan for w in wins])


def field_paths():
    return sorted(FIELD_DIR.glob("field_*.json"))


def load_field(path=None):
    """The newest field (or the one at `path`): {"generation", "attack": [team], "defend": [team], ...}."""
    paths = [Path(path)] if path else field_paths()
    if not paths:
        raise SystemExit("No field yet: run `python -m card_engine.training.incomplete field` first")
    return json.loads(paths[-1].read_text())


def _team_key(team):
    return json.dumps(team, sort_keys=True)


def proposals(classifier, role, count, seed, against=(), complete=8):
    """The model's own strong teams in a role: `count` ascended in incomplete mode (against the unseen field), and
    `complete` counters to each of a few named field members (complete mode), for variety."""
    import dataclasses
    from .generate import Settings, SlotSpace, counters, make_pool
    catalog = load_catalog()
    space = SlotSpace(classifier, make_pool(catalog, "all", borders=list(ALL_BORDERS)))
    settings = Settings(steps=300, noise_levels=12, sigma_max=4.0, role=ROLES[role])
    teams = [t for t, *_ in counters(space, HIDDEN_TEAM, count=count, restarts=2 * count, seed=seed,
                                     settings=dataclasses.replace(settings, incomplete=True))]
    for i, enemy in enumerate(against):
        teams += [t for t, *_ in counters(space, enemy, count=complete, restarts=2 * complete, seed=seed + 1 + i,
                                          settings=settings)]
    return teams


def bootstrap(classifier, role, count, seed):
    """Generation 0's opponents: the generator's broadly ascended strong teams in `role` (complete mode)."""
    from .generate import Settings, SlotSpace, broad_enemies, make_pool
    space = SlotSpace(classifier, make_pool(load_catalog(), "all", borders=list(ALL_BORDERS)))
    other = ROLES[1 - role]  # broad_enemies ascends the enemies in the role opposite settings.role
    return broad_enemies(space, count, settings=Settings(steps=300, noise_levels=12, sigma_max=4.0, role=other), seed=seed)


def build_field(classifier, pool, *, size=48, candidates=160, opponents=24, seed=1):
    """The next field generation: per role, the `size` distinct candidates the engine scores best against the
    previous field's other role (generation 0: against the generator's broad teams)."""
    rng = random.Random(f"field-{seed}")
    previous = load_field() if field_paths() else None
    generation = previous["generation"] + 1 if previous else 0
    catalog = load_catalog()
    field = {"generation": generation, "model_step": classifier.metadata.get("step"), "created": time.time()}
    for role in (0, 1):
        name, other = ROLES[role], ROLES[1 - role]
        rivals = previous[other] if previous else bootstrap(classifier, 1 - role, 2 * opponents, seed + role)
        elites = previous[name] if previous else []
        pool_teams = list(elites)
        pool_teams += proposals(classifier, role, candidates // 4, seed + 10 + role,
                                against=rng.sample(rivals, min(4, len(rivals))))
        pool_teams += [mutate(rng, catalog, rng.choice(elites), list(ALL_BORDERS), True, True)
                       for _ in range(candidates // 4)] if elites else []
        while len(pool_teams) < candidates:
            pool_teams.append(draw_candidate(rng, catalog, list(ALL_BORDERS), True, True))
        teams = list({_team_key(t): t for t in pool_teams}.values())
        sample = rng.sample(rivals, min(opponents, len(rivals)))  # one draw for every candidate: comparable scores
        scores = team_scores(pool, teams, role, [sample] * len(teams), seed * 1_000_003 + role * 500_000)
        ranked = [i for i in np.argsort(-np.nan_to_num(scores, nan=-1.0)) if not np.isnan(scores[i])]
        chosen = distinct(teams, ranked, size)
        field[name] = [teams[i] for i in chosen]
        field[f"{name}_scores"] = [round(float(scores[i]), 4) for i in chosen]
    FIELD_DIR.mkdir(parents=True, exist_ok=True)
    path = FIELD_DIR / f"field_{generation:04d}.json"
    tmp = path.with_name(f"partial_{path.name}")
    tmp.write_text(json.dumps(field))
    os.replace(tmp, path)
    return path, field


def hidden_shard(classifier, field, pool, seed, *, rounds=40, opponents=16, keep=8, keep_random=4):
    """One shard's rows: per round, one role's candidates scored against the other role's field by the engine and
    in incomplete mode by the model; the `keep` distinct ones the model gets most wrong and `keep_random` others."""
    rng = random.Random(f"hidden-{seed}")
    catalog = load_catalog()
    made = {role: proposals(classifier, role, 16, seed + role) for role in (0, 1)}  # the model's teams, once per shard
    rows, gaps = [], []
    for r in range(rounds):
        role = rng.randrange(2)
        own, rivals = field[ROLES[role]], field[ROLES[1 - role]]
        teams = rng.sample(own, min(12, len(own)))
        teams += [mutate(rng, catalog, rng.choice(own), list(ALL_BORDERS), True, True) for _ in range(12)]
        teams += rng.sample(made[role], min(12, len(made[role])))
        while len(teams) < 48:
            teams.append({key: value[0] for key, value in random_spec(rng, catalog).items()})
        teams = list({_team_key(t): t for t in teams}.values())
        against = [rng.sample(rivals, min(opponents, len(rivals))) for _ in teams]
        engine = team_scores(pool, teams, role, against, seed * 1_000_003 + r * 100_000)
        model = classifier.field_win(teams, role)
        gap = np.abs(engine - model)
        ranked = [i for i in np.argsort(-np.nan_to_num(gap, nan=-1.0)) if not np.isnan(engine[i])]
        chosen = distinct(teams, ranked, keep)
        rest = [i for i in ranked if i not in set(chosen)]
        chosen += rng.sample(rest, min(keep_random, len(rest)))
        gaps.append(float(np.nanmean(gap)))
        for i in chosen:
            battle = spec(teams[i], HIDDEN_TEAM) if role == 0 else spec(HIDDEN_TEAM, teams[i])
            a_win = engine[i] if role == 0 else 1 - engine[i]
            rows.append((battle, a_win, 1 - role, float(model[i])))
    arrays = {name: np.array([b[name] for b, *_ in rows], dtype=np.int16) for name in FIELDS}
    probs = np.array([[a, 1 - a, 0.0, 0.0] for _, a, *_ in rows], dtype=np.float32)
    extra = {"hidden_side": np.array([h for *_, h, _ in rows], dtype=np.int8),
             "model_win": np.array([m for *_, m in rows], dtype=np.float32),
             "field_generation": np.array(field["generation"])}
    return arrays, probs, extra, float(np.mean(gaps))


def _pool(workers):
    # An executor: a worker the OS kills raises BrokenProcessPool and ends the run, so a shell loop restarts it.
    return ProcessPoolExecutor(workers or max(1, (os.cpu_count() or 2) - 1), mp_context=mp.get_context("spawn"),
                               initializer=_init)


def main():
    from .flags import snapshot
    from .predict import Classifier
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("command", choices=("field", "labels"))
    parser.add_argument("--checkpoint", required=True, help="the model whose own strong teams make the field")
    parser.add_argument("--device")
    parser.add_argument("--workers", type=int, help="engine processes")
    parser.add_argument("--seed", type=int, default=1)
    parser.add_argument("--size", type=int, default=48, help="field: teams kept per role")
    parser.add_argument("--candidates", type=int, default=160, help="field: candidates scored per role")
    parser.add_argument("--opponents", type=int, help="field: opponents scoring every candidate (24); labels: "
                        "opponents per team (16)")
    parser.add_argument("--shards", type=int, default=1, help="labels: shards to write")
    parser.add_argument("--rounds", type=int, default=40, help="labels: rounds per shard")
    args = parser.parse_args()
    classifier = Classifier(args.checkpoint, args.device)
    with _pool(args.workers) as pool:
        if args.command == "field":
            started = time.time()
            path, field = build_field(classifier, pool, size=args.size, candidates=args.candidates,
                                      opponents=args.opponents or 24, seed=args.seed)
            print(json.dumps({"field": path.name, "generation": field["generation"], "model_step": field["model_step"],
                              "seconds": round(time.time() - started),
                              **{f"{role}_mean": round(float(np.mean(field[f"{role}_scores"])), 3) for role in ROLES}}))
            return
        field = load_field()
        STORE.mkdir(parents=True, exist_ok=True)
        first = field["generation"] * GENERATION_SEEDS
        existing = {int(p.stem.split("_")[1]) for p in STORE.glob("hidden_*.npz")}
        seed = next_seed({s for s in existing if s < first + GENERATION_SEEDS}, first)
        for done in range(1, args.shards + 1):
            started = time.time()
            arrays, probs, extra, gap = hidden_shard(classifier, field, pool, seed, rounds=args.rounds,
                                                     opponents=args.opponents or 16)
            target = STORE / f"hidden_{seed:08d}.npz"
            tmp = target.with_name(f"partial_{target.name}")
            np.savez_compressed(tmp, probs=probs, exact=np.zeros(len(probs), dtype=bool), snapshot=np.array(snapshot()),
                                **arrays, **extra)
            os.replace(tmp, target)
            print(json.dumps({"shard": target.name, "done": done, "of": args.shards, "rows": len(probs),
                              "generation": field["generation"], "model_step": classifier.metadata.get("step"),
                              "seconds": round(time.time() - started), "mean_gap": round(gap, 3)}), flush=True)
            seed += 1


if __name__ == "__main__":
    main()
